export const CMT_DURATION = 5500;
/** @deprecated Legacy scheduler spacing; general commentary uses GENERAL_COMMENTARY_* below. */
export const CMT_COOLDOWN = 3500;
export const CMT_MIN_MS = 25000;
export const CMT_MAX_MS = 50000;
export const CMT_CHANCE = 0.35;

/** Ambient general commentary: occasional background lines during open play only. */
export const GENERAL_COMMENTARY_MIN_MS = 25000;
export const GENERAL_COMMENTARY_MAX_MS = 45000;
export const GENERAL_COMMENTARY_CHANCE = 0.35;
export const GENERAL_COMMENTARY_COOLDOWN_MS = 30000;

export const SPEECH_PRIORITY = {
  general: 1,
  analyst: 2,
  close: 2,
  outcome: 3,
  innings_end: 3,
  wicket: 4,
  milestone: 5,
  result: 5,
};

export const ANALYST_PROBABILITY = {
  strike_rotate: 0.8,
  strike_hold: 0.8,
  boundary_hold: 0.8,
  over_end_rotate: 0.8,
  new_batter: 0.9,
  partnership_building: 0.25,
  partnership_pressure: 0.3,
  partnership_release: 0.5,
};

export const CRITICAL_SFX_ASSETS = {
  bat_crack: require('../../assets/sounds/sfx/bat_crack.mp3'),
  crowd_four: require('../../assets/sounds/sfx/crowd_four.mp3'),
  crowd_six: require('../../assets/sounds/sfx/crowd_six.mp3'),
  crowd_wicketcheer: require('../../assets/sounds/sfx/crowd_wicketcheer.mp3'),
  crowd_wicketgroan: require('../../assets/sounds/sfx/crowd_wicketgroan.mp3'),
  roll: require('../../assets/sounds/sfx/roll.mp3'),
  owzat: require('../../assets/sounds/sfx/owzat.mp3'),
  crowd_single: require('../../assets/sounds/sfx/crowd_single.mp3'),
  crowd_two: require('../../assets/sounds/sfx/crowd_two.mp3'),
  drs_win: require('../../assets/sounds/sfx/drs_win.mp3'),
  drs_lose: require('../../assets/sounds/sfx/drs_lose.mp3'),
};

export const COMMENTARY_POOLS = {
  "lead": {
    "general": 15,
    "pressure_calm": 8,
    "pressure_watchful": 8,
    "pressure_building": 8,
    "pressure_high": 8,
    "pressure_extreme": 8,
    "dot_calm": 6,
    "dot_watchful": 6,
    "dot_building": 6,
    "dot_high": 6,
    "dot_extreme": 6,
    "singles_neutral": 10,
    "singles_pressure": 8,
    "singles_chase": 7,
    "two_neutral": 10,
    "two_pressure": 5,
    "two_chase": 5,
    "four": 6,
    "six": 6,
    "bowled": 5,
    "caught": 5,
    "lbw": 12,
    "stumped": 10,
    "run_out": 12,
    "fifty": 10,
    "century": 10,
    "no_ball": 1,
    "dropped_catch": 1,
    "drs_win": 1,
    "drs_lose": 1,
    "injury": 1,
    "weather": 1,
    "drinks": 1,
    "legendary_ball": 1,
    "new_ball": 1,
    "wins": 3,
    "loss": 3,
    "close": 10,
    "impossible": 10,
    "first_innings_end": 6,
    "easy_chase": 2,
    "balanced_chase": 2,
    "tough_chase": 2,
    "very_tough_chase": 2
  },
  "analyst": {
    "strike_rotate": 6,
    "strike_hold": 6,
    "boundary_hold": 6,
    "over_end_rotate": 6,
    "new_batter": 6,
    "partnership_building": 6,
    "partnership_pressure": 6,
    "partnership_release": 6
  }
};

const makePoolClipKeys = (role, poolName, count) => (
  Array.from({ length: count }, (_, i) => `cmt.${role}.${poolName}_${i + 1}`)
);

export const COMMENTARY_SFX_ASSETS = {
  'cmt.lead.general_1': require('./../../assets/sounds/commentary/lead/general/general_1.mp3'),
  'cmt.lead.general_2': require('./../../assets/sounds/commentary/lead/general/general_2.mp3'),
  'cmt.lead.general_3': require('./../../assets/sounds/commentary/lead/general/general_3.mp3'),
  'cmt.lead.general_4': require('./../../assets/sounds/commentary/lead/general/general_4.mp3'),
  'cmt.lead.general_5': require('./../../assets/sounds/commentary/lead/general/general_5.mp3'),
  'cmt.lead.general_6': require('./../../assets/sounds/commentary/lead/general/general_6.mp3'),
  'cmt.lead.general_7': require('./../../assets/sounds/commentary/lead/general/general_7.mp3'),
  'cmt.lead.general_8': require('./../../assets/sounds/commentary/lead/general/general_8.mp3'),
  'cmt.lead.general_9': require('./../../assets/sounds/commentary/lead/general/general_9.mp3'),
  'cmt.lead.general_10': require('./../../assets/sounds/commentary/lead/general/general_10.mp3'),
  'cmt.lead.general_11': require('./../../assets/sounds/commentary/lead/general/general_11.mp3'),
  'cmt.lead.general_12': require('./../../assets/sounds/commentary/lead/general/general_12.mp3'),
  'cmt.lead.general_13': require('./../../assets/sounds/commentary/lead/general/general_13.mp3'),
  'cmt.lead.general_14': require('./../../assets/sounds/commentary/lead/general/general_14.mp3'),
  'cmt.lead.general_15': require('./../../assets/sounds/commentary/lead/general/general_15.mp3'),
  'cmt.lead.pressure_calm_1': require('./../../assets/sounds/commentary/lead/pressure/calm/pressure_calm_1.mp3'),
  'cmt.lead.pressure_calm_2': require('./../../assets/sounds/commentary/lead/pressure/calm/pressure_calm_2.mp3'),
  'cmt.lead.pressure_calm_3': require('./../../assets/sounds/commentary/lead/pressure/calm/pressure_calm_3.mp3'),
  'cmt.lead.pressure_calm_4': require('./../../assets/sounds/commentary/lead/pressure/calm/pressure_calm_4.mp3'),
  'cmt.lead.pressure_calm_5': require('./../../assets/sounds/commentary/lead/pressure/calm/pressure_calm_5.mp3'),
  'cmt.lead.pressure_calm_6': require('./../../assets/sounds/commentary/lead/pressure/calm/pressure_calm_6.mp3'),
  'cmt.lead.pressure_calm_7': require('./../../assets/sounds/commentary/lead/pressure/calm/pressure_calm_7.mp3'),
  'cmt.lead.pressure_calm_8': require('./../../assets/sounds/commentary/lead/pressure/calm/pressure_calm_8.mp3'),
  'cmt.lead.pressure_watchful_1': require('./../../assets/sounds/commentary/lead/pressure/watchful/pressure_watchful_1.mp3'),
  'cmt.lead.pressure_watchful_2': require('./../../assets/sounds/commentary/lead/pressure/watchful/pressure_watchful_2.mp3'),
  'cmt.lead.pressure_watchful_3': require('./../../assets/sounds/commentary/lead/pressure/watchful/pressure_watchful_3.mp3'),
  'cmt.lead.pressure_watchful_4': require('./../../assets/sounds/commentary/lead/pressure/watchful/pressure_watchful_4.mp3'),
  'cmt.lead.pressure_watchful_5': require('./../../assets/sounds/commentary/lead/pressure/watchful/pressure_watchful_5.mp3'),
  'cmt.lead.pressure_watchful_6': require('./../../assets/sounds/commentary/lead/pressure/watchful/pressure_watchful_6.mp3'),
  'cmt.lead.pressure_watchful_7': require('./../../assets/sounds/commentary/lead/pressure/watchful/pressure_watchful_7.mp3'),
  'cmt.lead.pressure_watchful_8': require('./../../assets/sounds/commentary/lead/pressure/watchful/pressure_watchful_8.mp3'),
  'cmt.lead.pressure_building_1': require('./../../assets/sounds/commentary/lead/pressure/building/pressure_building_1.mp3'),
  'cmt.lead.pressure_building_2': require('./../../assets/sounds/commentary/lead/pressure/building/pressure_building_2.mp3'),
  'cmt.lead.pressure_building_3': require('./../../assets/sounds/commentary/lead/pressure/building/pressure_building_3.mp3'),
  'cmt.lead.pressure_building_4': require('./../../assets/sounds/commentary/lead/pressure/building/pressure_building_4.mp3'),
  'cmt.lead.pressure_building_5': require('./../../assets/sounds/commentary/lead/pressure/building/pressure_building_5.mp3'),
  'cmt.lead.pressure_building_6': require('./../../assets/sounds/commentary/lead/pressure/building/pressure_building_6.mp3'),
  'cmt.lead.pressure_building_7': require('./../../assets/sounds/commentary/lead/pressure/building/pressure_building_7.mp3'),
  'cmt.lead.pressure_building_8': require('./../../assets/sounds/commentary/lead/pressure/building/pressure_building_8.mp3'),
  'cmt.lead.pressure_high_1': require('./../../assets/sounds/commentary/lead/pressure/high/pressure_high_1.mp3'),
  'cmt.lead.pressure_high_2': require('./../../assets/sounds/commentary/lead/pressure/high/pressure_high_2.mp3'),
  'cmt.lead.pressure_high_3': require('./../../assets/sounds/commentary/lead/pressure/high/pressure_high_3.mp3'),
  'cmt.lead.pressure_high_4': require('./../../assets/sounds/commentary/lead/pressure/high/pressure_high_4.mp3'),
  'cmt.lead.pressure_high_5': require('./../../assets/sounds/commentary/lead/pressure/high/pressure_high_5.mp3'),
  'cmt.lead.pressure_high_6': require('./../../assets/sounds/commentary/lead/pressure/high/pressure_high_6.mp3'),
  'cmt.lead.pressure_high_7': require('./../../assets/sounds/commentary/lead/pressure/high/pressure_high_7.mp3'),
  'cmt.lead.pressure_high_8': require('./../../assets/sounds/commentary/lead/pressure/high/pressure_high_8.mp3'),
  'cmt.lead.pressure_extreme_1': require('./../../assets/sounds/commentary/lead/pressure/extreme/pressure_extreme_1.mp3'),
  'cmt.lead.pressure_extreme_2': require('./../../assets/sounds/commentary/lead/pressure/extreme/pressure_extreme_2.mp3'),
  'cmt.lead.pressure_extreme_3': require('./../../assets/sounds/commentary/lead/pressure/extreme/pressure_extreme_3.mp3'),
  'cmt.lead.pressure_extreme_4': require('./../../assets/sounds/commentary/lead/pressure/extreme/pressure_extreme_4.mp3'),
  'cmt.lead.pressure_extreme_5': require('./../../assets/sounds/commentary/lead/pressure/extreme/pressure_extreme_5.mp3'),
  'cmt.lead.pressure_extreme_6': require('./../../assets/sounds/commentary/lead/pressure/extreme/pressure_extreme_6.mp3'),
  'cmt.lead.pressure_extreme_7': require('./../../assets/sounds/commentary/lead/pressure/extreme/pressure_extreme_7.mp3'),
  'cmt.lead.pressure_extreme_8': require('./../../assets/sounds/commentary/lead/pressure/extreme/pressure_extreme_8.mp3'),
  'cmt.lead.dot_calm_1': require('./../../assets/sounds/commentary/lead/dot/calm/dot_calm_1.mp3'),
  'cmt.lead.dot_calm_2': require('./../../assets/sounds/commentary/lead/dot/calm/dot_calm_2.mp3'),
  'cmt.lead.dot_calm_3': require('./../../assets/sounds/commentary/lead/dot/calm/dot_calm_3.mp3'),
  'cmt.lead.dot_calm_4': require('./../../assets/sounds/commentary/lead/dot/calm/dot_calm_4.mp3'),
  'cmt.lead.dot_calm_5': require('./../../assets/sounds/commentary/lead/dot/calm/dot_calm_5.mp3'),
  'cmt.lead.dot_calm_6': require('./../../assets/sounds/commentary/lead/dot/calm/dot_calm_6.mp3'),
  'cmt.lead.dot_watchful_1': require('./../../assets/sounds/commentary/lead/dot/watchful/dot_watchful_1.mp3'),
  'cmt.lead.dot_watchful_2': require('./../../assets/sounds/commentary/lead/dot/watchful/dot_watchful_2.mp3'),
  'cmt.lead.dot_watchful_3': require('./../../assets/sounds/commentary/lead/dot/watchful/dot_watchful_3.mp3'),
  'cmt.lead.dot_watchful_4': require('./../../assets/sounds/commentary/lead/dot/watchful/dot_watchful_4.mp3'),
  'cmt.lead.dot_watchful_5': require('./../../assets/sounds/commentary/lead/dot/watchful/dot_watchful_5.mp3'),
  'cmt.lead.dot_watchful_6': require('./../../assets/sounds/commentary/lead/dot/watchful/dot_watchful_6.mp3'),
  'cmt.lead.dot_building_1': require('./../../assets/sounds/commentary/lead/dot/building/dot_building_1.mp3'),
  'cmt.lead.dot_building_2': require('./../../assets/sounds/commentary/lead/dot/building/dot_building_2.mp3'),
  'cmt.lead.dot_building_3': require('./../../assets/sounds/commentary/lead/dot/building/dot_building_3.mp3'),
  'cmt.lead.dot_building_4': require('./../../assets/sounds/commentary/lead/dot/building/dot_building_4.mp3'),
  'cmt.lead.dot_building_5': require('./../../assets/sounds/commentary/lead/dot/building/dot_building_5.mp3'),
  'cmt.lead.dot_building_6': require('./../../assets/sounds/commentary/lead/dot/building/dot_building_6.mp3'),
  'cmt.lead.dot_high_1': require('./../../assets/sounds/commentary/lead/dot/high/dot_high_1.mp3'),
  'cmt.lead.dot_high_2': require('./../../assets/sounds/commentary/lead/dot/high/dot_high_2.mp3'),
  'cmt.lead.dot_high_3': require('./../../assets/sounds/commentary/lead/dot/high/dot_high_3.mp3'),
  'cmt.lead.dot_high_4': require('./../../assets/sounds/commentary/lead/dot/high/dot_high_4.mp3'),
  'cmt.lead.dot_high_5': require('./../../assets/sounds/commentary/lead/dot/high/dot_high_5.mp3'),
  'cmt.lead.dot_high_6': require('./../../assets/sounds/commentary/lead/dot/high/dot_high_6.mp3'),
  'cmt.lead.dot_extreme_1': require('./../../assets/sounds/commentary/lead/dot/extreme/dot_extreme_1.mp3'),
  'cmt.lead.dot_extreme_2': require('./../../assets/sounds/commentary/lead/dot/extreme/dot_extreme_2.mp3'),
  'cmt.lead.dot_extreme_3': require('./../../assets/sounds/commentary/lead/dot/extreme/dot_extreme_3.mp3'),
  'cmt.lead.dot_extreme_4': require('./../../assets/sounds/commentary/lead/dot/extreme/dot_extreme_4.mp3'),
  'cmt.lead.dot_extreme_5': require('./../../assets/sounds/commentary/lead/dot/extreme/dot_extreme_5.mp3'),
  'cmt.lead.dot_extreme_6': require('./../../assets/sounds/commentary/lead/dot/extreme/dot_extreme_6.mp3'),
  'cmt.lead.singles_neutral_1': require('./../../assets/sounds/commentary/lead/runs/singles/neutral/singles_neutral_1.mp3'),
  'cmt.lead.singles_neutral_2': require('./../../assets/sounds/commentary/lead/runs/singles/neutral/singles_neutral_2.mp3'),
  'cmt.lead.singles_neutral_3': require('./../../assets/sounds/commentary/lead/runs/singles/neutral/singles_neutral_3.mp3'),
  'cmt.lead.singles_neutral_4': require('./../../assets/sounds/commentary/lead/runs/singles/neutral/singles_neutral_4.mp3'),
  'cmt.lead.singles_neutral_5': require('./../../assets/sounds/commentary/lead/runs/singles/neutral/singles_neutral_5.mp3'),
  'cmt.lead.singles_neutral_6': require('./../../assets/sounds/commentary/lead/runs/singles/neutral/singles_neutral_6.mp3'),
  'cmt.lead.singles_neutral_7': require('./../../assets/sounds/commentary/lead/runs/singles/neutral/singles_neutral_7.mp3'),
  'cmt.lead.singles_neutral_8': require('./../../assets/sounds/commentary/lead/runs/singles/neutral/singles_neutral_8.mp3'),
  'cmt.lead.singles_neutral_9': require('./../../assets/sounds/commentary/lead/runs/singles/neutral/singles_neutral_9.mp3'),
  'cmt.lead.singles_neutral_10': require('./../../assets/sounds/commentary/lead/runs/singles/neutral/singles_neutral_10.mp3'),
  'cmt.lead.singles_pressure_1': require('./../../assets/sounds/commentary/lead/runs/singles/pressure/singles_pressure_1.mp3'),
  'cmt.lead.singles_pressure_2': require('./../../assets/sounds/commentary/lead/runs/singles/pressure/singles_pressure_2.mp3'),
  'cmt.lead.singles_pressure_3': require('./../../assets/sounds/commentary/lead/runs/singles/pressure/singles_pressure_3.mp3'),
  'cmt.lead.singles_pressure_4': require('./../../assets/sounds/commentary/lead/runs/singles/pressure/singles_pressure_4.mp3'),
  'cmt.lead.singles_pressure_5': require('./../../assets/sounds/commentary/lead/runs/singles/pressure/singles_pressure_5.mp3'),
  'cmt.lead.singles_pressure_6': require('./../../assets/sounds/commentary/lead/runs/singles/pressure/singles_pressure_6.mp3'),
  'cmt.lead.singles_pressure_7': require('./../../assets/sounds/commentary/lead/runs/singles/pressure/singles_pressure_7.mp3'),
  'cmt.lead.singles_pressure_8': require('./../../assets/sounds/commentary/lead/runs/singles/pressure/singles_pressure_8.mp3'),
  'cmt.lead.singles_chase_1': require('./../../assets/sounds/commentary/lead/runs/singles/chase/singles_chase_1.mp3'),
  'cmt.lead.singles_chase_2': require('./../../assets/sounds/commentary/lead/runs/singles/chase/singles_chase_2.mp3'),
  'cmt.lead.singles_chase_3': require('./../../assets/sounds/commentary/lead/runs/singles/chase/singles_chase_3.mp3'),
  'cmt.lead.singles_chase_4': require('./../../assets/sounds/commentary/lead/runs/singles/chase/singles_chase_4.mp3'),
  'cmt.lead.singles_chase_5': require('./../../assets/sounds/commentary/lead/runs/singles/chase/singles_chase_5.mp3'),
  'cmt.lead.singles_chase_6': require('./../../assets/sounds/commentary/lead/runs/singles/chase/singles_chase_6.mp3'),
  'cmt.lead.singles_chase_7': require('./../../assets/sounds/commentary/lead/runs/singles/chase/singles_chase_7.mp3'),
  'cmt.lead.two_neutral_1': require('./../../assets/sounds/commentary/lead/runs/twos/neutral/two_neutral_1.mp3'),
  'cmt.lead.two_neutral_2': require('./../../assets/sounds/commentary/lead/runs/twos/neutral/two_neutral_2.mp3'),
  'cmt.lead.two_neutral_3': require('./../../assets/sounds/commentary/lead/runs/twos/neutral/two_neutral_3.mp3'),
  'cmt.lead.two_neutral_4': require('./../../assets/sounds/commentary/lead/runs/twos/neutral/two_neutral_4.mp3'),
  'cmt.lead.two_neutral_5': require('./../../assets/sounds/commentary/lead/runs/twos/neutral/two_neutral_5.mp3'),
  'cmt.lead.two_neutral_6': require('./../../assets/sounds/commentary/lead/runs/twos/neutral/two_neutral_6.mp3'),
  'cmt.lead.two_neutral_7': require('./../../assets/sounds/commentary/lead/runs/twos/neutral/two_neutral_7.mp3'),
  'cmt.lead.two_neutral_8': require('./../../assets/sounds/commentary/lead/runs/twos/neutral/two_neutral_8.mp3'),
  'cmt.lead.two_neutral_9': require('./../../assets/sounds/commentary/lead/runs/twos/neutral/two_neutral_9.mp3'),
  'cmt.lead.two_neutral_10': require('./../../assets/sounds/commentary/lead/runs/twos/neutral/two_neutral_10.mp3'),
  'cmt.lead.two_pressure_1': require('./../../assets/sounds/commentary/lead/runs/twos/pressure/two_pressure_1.mp3'),
  'cmt.lead.two_pressure_2': require('./../../assets/sounds/commentary/lead/runs/twos/pressure/two_pressure_2.mp3'),
  'cmt.lead.two_pressure_3': require('./../../assets/sounds/commentary/lead/runs/twos/pressure/two_pressure_3.mp3'),
  'cmt.lead.two_pressure_4': require('./../../assets/sounds/commentary/lead/runs/twos/pressure/two_pressure_4.mp3'),
  'cmt.lead.two_pressure_5': require('./../../assets/sounds/commentary/lead/runs/twos/pressure/two_pressure_5.mp3'),
  'cmt.lead.two_chase_1': require('./../../assets/sounds/commentary/lead/runs/twos/chase/two_chase_1.mp3'),
  'cmt.lead.two_chase_2': require('./../../assets/sounds/commentary/lead/runs/twos/chase/two_chase_2.mp3'),
  'cmt.lead.two_chase_3': require('./../../assets/sounds/commentary/lead/runs/twos/chase/two_chase_3.mp3'),
  'cmt.lead.two_chase_4': require('./../../assets/sounds/commentary/lead/runs/twos/chase/two_chase_4.mp3'),
  'cmt.lead.two_chase_5': require('./../../assets/sounds/commentary/lead/runs/twos/chase/two_chase_5.mp3'),
  'cmt.lead.four_1': require('./../../assets/sounds/commentary/lead/runs/boundary/four/four_1.mp3'),
  'cmt.lead.four_2': require('./../../assets/sounds/commentary/lead/runs/boundary/four/four_2.mp3'),
  'cmt.lead.four_3': require('./../../assets/sounds/commentary/lead/runs/boundary/four/four_3.mp3'),
  'cmt.lead.four_4': require('./../../assets/sounds/commentary/lead/runs/boundary/four/four_4.mp3'),
  'cmt.lead.four_5': require('./../../assets/sounds/commentary/lead/runs/boundary/four/four_5.mp3'),
  'cmt.lead.four_6': require('./../../assets/sounds/commentary/lead/runs/boundary/four/four_6.mp3'),
  'cmt.lead.six_1': require('./../../assets/sounds/commentary/lead/runs/boundary/six/six_1.mp3'),
  'cmt.lead.six_2': require('./../../assets/sounds/commentary/lead/runs/boundary/six/six_2.mp3'),
  'cmt.lead.six_3': require('./../../assets/sounds/commentary/lead/runs/boundary/six/six_3.mp3'),
  'cmt.lead.six_4': require('./../../assets/sounds/commentary/lead/runs/boundary/six/six_4.mp3'),
  'cmt.lead.six_5': require('./../../assets/sounds/commentary/lead/runs/boundary/six/six_5.mp3'),
  'cmt.lead.six_6': require('./../../assets/sounds/commentary/lead/runs/boundary/six/six_6.mp3'),
  'cmt.lead.bowled_1': require('./../../assets/sounds/commentary/lead/wickets/bowled/bowled_1.mp3'),
  'cmt.lead.bowled_2': require('./../../assets/sounds/commentary/lead/wickets/bowled/bowled_2.mp3'),
  'cmt.lead.bowled_3': require('./../../assets/sounds/commentary/lead/wickets/bowled/bowled_3.mp3'),
  'cmt.lead.bowled_4': require('./../../assets/sounds/commentary/lead/wickets/bowled/bowled_4.mp3'),
  'cmt.lead.bowled_5': require('./../../assets/sounds/commentary/lead/wickets/bowled/bowled_5.mp3'),
  'cmt.lead.caught_1': require('./../../assets/sounds/commentary/lead/wickets/caught/caught_1.mp3'),
  'cmt.lead.caught_2': require('./../../assets/sounds/commentary/lead/wickets/caught/caught_2.mp3'),
  'cmt.lead.caught_3': require('./../../assets/sounds/commentary/lead/wickets/caught/caught_3.mp3'),
  'cmt.lead.caught_4': require('./../../assets/sounds/commentary/lead/wickets/caught/caught_4.mp3'),
  'cmt.lead.caught_5': require('./../../assets/sounds/commentary/lead/wickets/caught/caught_5.mp3'),
  'cmt.lead.lbw_1': require('./../../assets/sounds/commentary/lead/wickets/lbw/lbw_1.mp3'),
  'cmt.lead.lbw_2': require('./../../assets/sounds/commentary/lead/wickets/lbw/lbw_2.mp3'),
  'cmt.lead.lbw_3': require('./../../assets/sounds/commentary/lead/wickets/lbw/lbw_3.mp3'),
  'cmt.lead.lbw_4': require('./../../assets/sounds/commentary/lead/wickets/lbw/lbw_4.mp3'),
  'cmt.lead.lbw_5': require('./../../assets/sounds/commentary/lead/wickets/lbw/lbw_5.mp3'),
  'cmt.lead.lbw_6': require('./../../assets/sounds/commentary/lead/wickets/lbw/lbw_6.mp3'),
  'cmt.lead.lbw_7': require('./../../assets/sounds/commentary/lead/wickets/lbw/lbw_7.mp3'),
  'cmt.lead.lbw_8': require('./../../assets/sounds/commentary/lead/wickets/lbw/lbw_8.mp3'),
  'cmt.lead.lbw_9': require('./../../assets/sounds/commentary/lead/wickets/lbw/lbw_9.mp3'),
  'cmt.lead.lbw_10': require('./../../assets/sounds/commentary/lead/wickets/lbw/lbw_10.mp3'),
  'cmt.lead.lbw_11': require('./../../assets/sounds/commentary/lead/wickets/lbw/lbw_11.mp3'),
  'cmt.lead.lbw_12': require('./../../assets/sounds/commentary/lead/wickets/lbw/lbw_12.mp3'),
  'cmt.lead.stumped_1': require('./../../assets/sounds/commentary/lead/wickets/stumped/stumped_1.mp3'),
  'cmt.lead.stumped_2': require('./../../assets/sounds/commentary/lead/wickets/stumped/stumped_2.mp3'),
  'cmt.lead.stumped_3': require('./../../assets/sounds/commentary/lead/wickets/stumped/stumped_3.mp3'),
  'cmt.lead.stumped_4': require('./../../assets/sounds/commentary/lead/wickets/stumped/stumped_4.mp3'),
  'cmt.lead.stumped_5': require('./../../assets/sounds/commentary/lead/wickets/stumped/stumped_5.mp3'),
  'cmt.lead.stumped_6': require('./../../assets/sounds/commentary/lead/wickets/stumped/stumped_6.mp3'),
  'cmt.lead.stumped_7': require('./../../assets/sounds/commentary/lead/wickets/stumped/stumped_7.mp3'),
  'cmt.lead.stumped_8': require('./../../assets/sounds/commentary/lead/wickets/stumped/stumped_8.mp3'),
  'cmt.lead.stumped_9': require('./../../assets/sounds/commentary/lead/wickets/stumped/stumped_9.mp3'),
  'cmt.lead.stumped_10': require('./../../assets/sounds/commentary/lead/wickets/stumped/stumped_10.mp3'),
  'cmt.lead.run_out_1': require('./../../assets/sounds/commentary/lead/wickets/runout/runout_1.mp3'),
  'cmt.lead.run_out_2': require('./../../assets/sounds/commentary/lead/wickets/runout/runout_2.mp3'),
  'cmt.lead.run_out_3': require('./../../assets/sounds/commentary/lead/wickets/runout/runout_3.mp3'),
  'cmt.lead.run_out_4': require('./../../assets/sounds/commentary/lead/wickets/runout/runout_4.mp3'),
  'cmt.lead.run_out_5': require('./../../assets/sounds/commentary/lead/wickets/runout/runout_5.mp3'),
  'cmt.lead.run_out_6': require('./../../assets/sounds/commentary/lead/wickets/runout/runout_6.mp3'),
  'cmt.lead.run_out_7': require('./../../assets/sounds/commentary/lead/wickets/runout/runout_7.mp3'),
  'cmt.lead.run_out_8': require('./../../assets/sounds/commentary/lead/wickets/runout/runout_8.mp3'),
  'cmt.lead.run_out_9': require('./../../assets/sounds/commentary/lead/wickets/runout/runout_9.mp3'),
  'cmt.lead.run_out_10': require('./../../assets/sounds/commentary/lead/wickets/runout/runout_10.mp3'),
  'cmt.lead.run_out_11': require('./../../assets/sounds/commentary/lead/wickets/runout/runout_11.mp3'),
  'cmt.lead.run_out_12': require('./../../assets/sounds/commentary/lead/wickets/runout/runout_12.mp3'),
  'cmt.lead.fifty_1': require('./../../assets/sounds/commentary/lead/milestones/fifty/fifty_1.mp3'),
  'cmt.lead.fifty_2': require('./../../assets/sounds/commentary/lead/milestones/fifty/fifty_2.mp3'),
  'cmt.lead.fifty_3': require('./../../assets/sounds/commentary/lead/milestones/fifty/fifty_3.mp3'),
  'cmt.lead.fifty_4': require('./../../assets/sounds/commentary/lead/milestones/fifty/fifty_4.mp3'),
  'cmt.lead.fifty_5': require('./../../assets/sounds/commentary/lead/milestones/fifty/fifty_5.mp3'),
  'cmt.lead.fifty_6': require('./../../assets/sounds/commentary/lead/milestones/fifty/fifty_6.mp3'),
  'cmt.lead.fifty_7': require('./../../assets/sounds/commentary/lead/milestones/fifty/fifty_7.mp3'),
  'cmt.lead.fifty_8': require('./../../assets/sounds/commentary/lead/milestones/fifty/fifty_8.mp3'),
  'cmt.lead.fifty_9': require('./../../assets/sounds/commentary/lead/milestones/fifty/fifty_9.mp3'),
  'cmt.lead.fifty_10': require('./../../assets/sounds/commentary/lead/milestones/fifty/fifty_10.mp3'),
  'cmt.lead.century_1': require('./../../assets/sounds/commentary/lead/milestones/century/century_1.mp3'),
  'cmt.lead.century_2': require('./../../assets/sounds/commentary/lead/milestones/century/century_2.mp3'),
  'cmt.lead.century_3': require('./../../assets/sounds/commentary/lead/milestones/century/century_3.mp3'),
  'cmt.lead.century_4': require('./../../assets/sounds/commentary/lead/milestones/century/century_4.mp3'),
  'cmt.lead.century_5': require('./../../assets/sounds/commentary/lead/milestones/century/century_5.mp3'),
  'cmt.lead.century_6': require('./../../assets/sounds/commentary/lead/milestones/century/century_6.mp3'),
  'cmt.lead.century_7': require('./../../assets/sounds/commentary/lead/milestones/century/century_7.mp3'),
  'cmt.lead.century_8': require('./../../assets/sounds/commentary/lead/milestones/century/century_8.mp3'),
  'cmt.lead.century_9': require('./../../assets/sounds/commentary/lead/milestones/century/century_9.mp3'),
  'cmt.lead.century_10': require('./../../assets/sounds/commentary/lead/milestones/century/century_10.mp3'),
  'cmt.lead.no_ball_1': require('./../../assets/sounds/commentary/lead/special/no_ball/no_ball_1.mp3'),
  'cmt.lead.no_ball': require('./../../assets/sounds/commentary/lead/special/no_ball/no_ball_1.mp3'),
  'cmt.lead.dropped_catch_1': require('./../../assets/sounds/commentary/lead/special/dropped_catch/dropped_catch_1.mp3'),
  'cmt.lead.dropped_catch': require('./../../assets/sounds/commentary/lead/special/dropped_catch/dropped_catch_1.mp3'),
  'cmt.lead.drs_win_1': require('./../../assets/sounds/commentary/lead/special/drs_win/drs_win_1.mp3'),
  'cmt.lead.drs_win': require('./../../assets/sounds/commentary/lead/special/drs_win/drs_win_1.mp3'),
  'cmt.lead.drs_lose_1': require('./../../assets/sounds/commentary/lead/special/drs_lose/drs_lose_1.mp3'),
  'cmt.lead.drs_lose': require('./../../assets/sounds/commentary/lead/special/drs_lose/drs_lose_1.mp3'),
  'cmt.lead.injury_1': require('./../../assets/sounds/commentary/lead/special/injury/injury_1.mp3'),
  'cmt.lead.injury': require('./../../assets/sounds/commentary/lead/special/injury/injury_1.mp3'),
  'cmt.lead.weather_1': require('./../../assets/sounds/commentary/lead/special/weather/weather_1.mp3'),
  'cmt.lead.weather': require('./../../assets/sounds/commentary/lead/special/weather/weather_1.mp3'),
  'cmt.lead.drinks_1': require('./../../assets/sounds/commentary/lead/special/drinks/drinks_1.mp3'),
  'cmt.lead.drinks': require('./../../assets/sounds/commentary/lead/special/drinks/drinks_1.mp3'),
  'cmt.lead.legendary_ball_1': require('./../../assets/sounds/commentary/lead/special/legendary_ball/legendary_ball_1.mp3'),
  'cmt.lead.legendary_ball': require('./../../assets/sounds/commentary/lead/special/legendary_ball/legendary_ball_1.mp3'),
  'cmt.lead.new_ball_1': require('./../../assets/sounds/commentary/lead/special/new_ball/new_ball_1.mp3'),
  'cmt.lead.new_ball': require('./../../assets/sounds/commentary/lead/special/new_ball/new_ball_1.mp3'),
  'cmt.lead.wins_1': require('./../../assets/sounds/commentary/lead/match/result/win/win_1.mp3'),
  'cmt.lead.wins_2': require('./../../assets/sounds/commentary/lead/match/result/win/win_2.mp3'),
  'cmt.lead.wins_3': require('./../../assets/sounds/commentary/lead/match/result/win/win_3.mp3'),
  'cmt.lead.loss_1': require('./../../assets/sounds/commentary/lead/match/result/loss/loss_1.mp3'),
  'cmt.lead.loss_2': require('./../../assets/sounds/commentary/lead/match/result/loss/loss_2.mp3'),
  'cmt.lead.loss_3': require('./../../assets/sounds/commentary/lead/match/result/loss/loss_3.mp3'),
  'cmt.lead.close_1': require('./../../assets/sounds/commentary/lead/match/close/close_1.mp3'),
  'cmt.lead.close_2': require('./../../assets/sounds/commentary/lead/match/close/close_2.mp3'),
  'cmt.lead.close_3': require('./../../assets/sounds/commentary/lead/match/close/close_3.mp3'),
  'cmt.lead.close_4': require('./../../assets/sounds/commentary/lead/match/close/close_4.mp3'),
  'cmt.lead.close_5': require('./../../assets/sounds/commentary/lead/match/close/close_5.mp3'),
  'cmt.lead.close_6': require('./../../assets/sounds/commentary/lead/match/close/close_6.mp3'),
  'cmt.lead.close_7': require('./../../assets/sounds/commentary/lead/match/close/close_7.mp3'),
  'cmt.lead.close_8': require('./../../assets/sounds/commentary/lead/match/close/close_8.mp3'),
  'cmt.lead.close_9': require('./../../assets/sounds/commentary/lead/match/close/close_9.mp3'),
  'cmt.lead.close_10': require('./../../assets/sounds/commentary/lead/match/close/close_10.mp3'),
  'cmt.lead.impossible_1': require('./../../assets/sounds/commentary/lead/match/impossible/impossible_1.mp3'),
  'cmt.lead.impossible_2': require('./../../assets/sounds/commentary/lead/match/impossible/impossible_2.mp3'),
  'cmt.lead.impossible_3': require('./../../assets/sounds/commentary/lead/match/impossible/impossible_3.mp3'),
  'cmt.lead.impossible_4': require('./../../assets/sounds/commentary/lead/match/impossible/impossible_4.mp3'),
  'cmt.lead.impossible_5': require('./../../assets/sounds/commentary/lead/match/impossible/impossible_5.mp3'),
  'cmt.lead.impossible_6': require('./../../assets/sounds/commentary/lead/match/impossible/impossible_6.mp3'),
  'cmt.lead.impossible_7': require('./../../assets/sounds/commentary/lead/match/impossible/impossible_7.mp3'),
  'cmt.lead.impossible_8': require('./../../assets/sounds/commentary/lead/match/impossible/impossible_8.mp3'),
  'cmt.lead.impossible_9': require('./../../assets/sounds/commentary/lead/match/impossible/impossible_9.mp3'),
  'cmt.lead.impossible_10': require('./../../assets/sounds/commentary/lead/match/impossible/impossible_10.mp3'),
  'cmt.lead.first_innings_end_1': require('./../../assets/sounds/commentary/lead/match/innings_end/first_innings_end_1.mp3'),
  'cmt.lead.first_innings_end_2': require('./../../assets/sounds/commentary/lead/match/innings_end/first_innings_end_2.mp3'),
  'cmt.lead.first_innings_end_3': require('./../../assets/sounds/commentary/lead/match/innings_end/first_innings_end_3.mp3'),
  'cmt.lead.first_innings_end_4': require('./../../assets/sounds/commentary/lead/match/innings_end/first_innings_end_4.mp3'),
  'cmt.lead.first_innings_end_5': require('./../../assets/sounds/commentary/lead/match/innings_end/first_innings_end_5.mp3'),
  'cmt.lead.first_innings_end_6': require('./../../assets/sounds/commentary/lead/match/innings_end/first_innings_end_6.mp3'),
  'cmt.lead.easy_chase_1': require('./../../assets/sounds/commentary/lead/match/chase_start/easy_chase_1.mp3'),
  'cmt.lead.easy_chase_2': require('./../../assets/sounds/commentary/lead/match/chase_start/easy_chase_2.mp3'),
  'cmt.lead.balanced_chase_1': require('./../../assets/sounds/commentary/lead/match/chase_start/balanced_chase_1.mp3'),
  'cmt.lead.balanced_chase_2': require('./../../assets/sounds/commentary/lead/match/chase_start/balanced_chase_2.mp3'),
  'cmt.lead.tough_chase_1': require('./../../assets/sounds/commentary/lead/match/chase_start/tough_chase_1.mp3'),
  'cmt.lead.tough_chase_2': require('./../../assets/sounds/commentary/lead/match/chase_start/tough_chase_2.mp3'),
  'cmt.lead.very_tough_chase_1': require('./../../assets/sounds/commentary/lead/match/chase_start/very_tough_chase_1.mp3'),
  'cmt.lead.very_tough_chase_2': require('./../../assets/sounds/commentary/lead/match/chase_start/very_tough_chase_2.mp3'),
  'cmt.analyst.strike_rotate_1': require('./../../assets/sounds/commentary/analyst/strike/rotate/strike_rotate_1.mp3'),
  'cmt.analyst.strike_rotate_2': require('./../../assets/sounds/commentary/analyst/strike/rotate/strike_rotate_2.mp3'),
  'cmt.analyst.strike_rotate_3': require('./../../assets/sounds/commentary/analyst/strike/rotate/strike_rotate_3.mp3'),
  'cmt.analyst.strike_rotate_4': require('./../../assets/sounds/commentary/analyst/strike/rotate/strike_rotate_4.mp3'),
  'cmt.analyst.strike_rotate_5': require('./../../assets/sounds/commentary/analyst/strike/rotate/strike_rotate_5.mp3'),
  'cmt.analyst.strike_rotate_6': require('./../../assets/sounds/commentary/analyst/strike/rotate/strike_rotate_6.mp3'),
  'cmt.analyst.strike_hold_1': require('./../../assets/sounds/commentary/analyst/strike/hold/strike_hold_1.mp3'),
  'cmt.analyst.strike_hold_2': require('./../../assets/sounds/commentary/analyst/strike/hold/strike_hold_2.mp3'),
  'cmt.analyst.strike_hold_3': require('./../../assets/sounds/commentary/analyst/strike/hold/strike_hold_3.mp3'),
  'cmt.analyst.strike_hold_4': require('./../../assets/sounds/commentary/analyst/strike/hold/strike_hold_4.mp3'),
  'cmt.analyst.strike_hold_5': require('./../../assets/sounds/commentary/analyst/strike/hold/strike_hold_5.mp3'),
  'cmt.analyst.strike_hold_6': require('./../../assets/sounds/commentary/analyst/strike/hold/strike_hold_6.mp3'),
  'cmt.analyst.boundary_hold_1': require('./../../assets/sounds/commentary/analyst/strike/boundary_hold/boundary_hold_1.mp3'),
  'cmt.analyst.boundary_hold_2': require('./../../assets/sounds/commentary/analyst/strike/boundary_hold/boundary_hold_2.mp3'),
  'cmt.analyst.boundary_hold_3': require('./../../assets/sounds/commentary/analyst/strike/boundary_hold/boundary_hold_3.mp3'),
  'cmt.analyst.boundary_hold_4': require('./../../assets/sounds/commentary/analyst/strike/boundary_hold/boundary_hold_4.mp3'),
  'cmt.analyst.boundary_hold_5': require('./../../assets/sounds/commentary/analyst/strike/boundary_hold/boundary_hold_5.mp3'),
  'cmt.analyst.boundary_hold_6': require('./../../assets/sounds/commentary/analyst/strike/boundary_hold/boundary_hold_6.mp3'),
  'cmt.analyst.over_end_rotate_1': require('./../../assets/sounds/commentary/analyst/over/end_rotate/over_end_rotate_1.mp3'),
  'cmt.analyst.over_end_rotate_2': require('./../../assets/sounds/commentary/analyst/over/end_rotate/over_end_rotate_2.mp3'),
  'cmt.analyst.over_end_rotate_3': require('./../../assets/sounds/commentary/analyst/over/end_rotate/over_end_rotate_3.mp3'),
  'cmt.analyst.over_end_rotate_4': require('./../../assets/sounds/commentary/analyst/over/end_rotate/over_end_rotate_4.mp3'),
  'cmt.analyst.over_end_rotate_5': require('./../../assets/sounds/commentary/analyst/over/end_rotate/over_end_rotate_5.mp3'),
  'cmt.analyst.over_end_rotate_6': require('./../../assets/sounds/commentary/analyst/over/end_rotate/over_end_rotate_6.mp3'),
  'cmt.analyst.new_batter_1': require('./../../assets/sounds/commentary/analyst/batter/new_batter/new_batter_1.mp3'),
  'cmt.analyst.new_batter_2': require('./../../assets/sounds/commentary/analyst/batter/new_batter/new_batter_2.mp3'),
  'cmt.analyst.new_batter_3': require('./../../assets/sounds/commentary/analyst/batter/new_batter/new_batter_3.mp3'),
  'cmt.analyst.new_batter_4': require('./../../assets/sounds/commentary/analyst/batter/new_batter/new_batter_4.mp3'),
  'cmt.analyst.new_batter_5': require('./../../assets/sounds/commentary/analyst/batter/new_batter/new_batter_5.mp3'),
  'cmt.analyst.new_batter_6': require('./../../assets/sounds/commentary/analyst/batter/new_batter/new_batter_6.mp3'),
  'cmt.analyst.partnership_building_1': require('./../../assets/sounds/commentary/analyst/partnership/building/partnership_building_1.mp3'),
  'cmt.analyst.partnership_building_2': require('./../../assets/sounds/commentary/analyst/partnership/building/partnership_building_2.mp3'),
  'cmt.analyst.partnership_building_3': require('./../../assets/sounds/commentary/analyst/partnership/building/partnership_building_3.mp3'),
  'cmt.analyst.partnership_building_4': require('./../../assets/sounds/commentary/analyst/partnership/building/partnership_building_4.mp3'),
  'cmt.analyst.partnership_building_5': require('./../../assets/sounds/commentary/analyst/partnership/building/partnership_building_5.mp3'),
  'cmt.analyst.partnership_building_6': require('./../../assets/sounds/commentary/analyst/partnership/building/partnership_building_6.mp3'),
  'cmt.analyst.partnership_pressure_1': require('./../../assets/sounds/commentary/analyst/partnership/pressure/partnership_pressure_1.mp3'),
  'cmt.analyst.partnership_pressure_2': require('./../../assets/sounds/commentary/analyst/partnership/pressure/partnership_pressure_2.mp3'),
  'cmt.analyst.partnership_pressure_3': require('./../../assets/sounds/commentary/analyst/partnership/pressure/partnership_pressure_3.mp3'),
  'cmt.analyst.partnership_pressure_4': require('./../../assets/sounds/commentary/analyst/partnership/pressure/partnership_pressure_4.mp3'),
  'cmt.analyst.partnership_pressure_5': require('./../../assets/sounds/commentary/analyst/partnership/pressure/partnership_pressure_5.mp3'),
  'cmt.analyst.partnership_pressure_6': require('./../../assets/sounds/commentary/analyst/partnership/pressure/partnership_pressure_6.mp3'),
  'cmt.analyst.partnership_release_1': require('./../../assets/sounds/commentary/analyst/partnership/release/partnership_release_1.mp3'),
  'cmt.analyst.partnership_release_2': require('./../../assets/sounds/commentary/analyst/partnership/release/partnership_release_2.mp3'),
  'cmt.analyst.partnership_release_3': require('./../../assets/sounds/commentary/analyst/partnership/release/partnership_release_3.mp3'),
  'cmt.analyst.partnership_release_4': require('./../../assets/sounds/commentary/analyst/partnership/release/partnership_release_4.mp3'),
  'cmt.analyst.partnership_release_5': require('./../../assets/sounds/commentary/analyst/partnership/release/partnership_release_5.mp3'),
  'cmt.analyst.partnership_release_6': require('./../../assets/sounds/commentary/analyst/partnership/release/partnership_release_6.mp3'),
};

const hasCommentaryClip = (clipKey) => !!COMMENTARY_SFX_ASSETS[clipKey];

const buildPool = (role, poolName) => {
  const expected = COMMENTARY_POOLS?.[role]?.[poolName] ?? 0;
  const clips = makePoolClipKeys(role, poolName, expected).filter(hasCommentaryClip);
  return clips;
};

export const COMMENTARY_POOL_KEYS = {
  lead: Object.fromEntries(Object.keys(COMMENTARY_POOLS.lead).map((poolName) => [poolName, buildPool('lead', poolName)])),
  analyst: Object.fromEntries(Object.keys(COMMENTARY_POOLS.analyst).map((poolName) => [poolName, buildPool('analyst', poolName)])),
};

export const CMT_POOLS = {
  ...COMMENTARY_POOL_KEYS.lead,
  ...COMMENTARY_POOL_KEYS.analyst,
};

export const GENERAL_CMTS = COMMENTARY_POOL_KEYS.lead.general;

export const POOL_PRIORITY = {
  general: 'general',
  pressure_calm: 'close',
  pressure_watchful: 'close',
  pressure_building: 'close',
  pressure_high: 'close',
  pressure_extreme: 'close',
  dot_calm: 'outcome',
  dot_watchful: 'outcome',
  dot_building: 'outcome',
  dot_high: 'outcome',
  dot_extreme: 'outcome',
  singles_neutral: 'outcome',
  singles_pressure: 'outcome',
  singles_chase: 'outcome',
  two_neutral: 'outcome',
  two_pressure: 'outcome',
  two_chase: 'outcome',
  four: 'outcome',
  six: 'outcome',
  bowled: 'wicket',
  caught: 'wicket',
  lbw: 'wicket',
  stumped: 'wicket',
  run_out: 'wicket',
  fifty: 'milestone',
  century: 'milestone',
  no_ball: 'result',
  dropped_catch: 'result',
  drs_win: 'result',
  drs_lose: 'result',
  injury: 'result',
  weather: 'result',
  drinks: 'result',
  legendary_ball: 'result',
  new_ball: 'result',
  wins: 'result',
  loss: 'result',
  close: 'close',
  impossible: 'close',
  first_innings_end: 'innings_end',
  easy_chase: 'result',
  balanced_chase: 'result',
  tough_chase: 'result',
  very_tough_chase: 'result',
  strike_rotate: 'analyst',
  strike_hold: 'analyst',
  boundary_hold: 'analyst',
  over_end_rotate: 'analyst',
  new_batter: 'analyst',
  partnership_building: 'analyst',
  partnership_pressure: 'analyst',
  partnership_release: 'analyst',
};

const LEGACY_POOL_NAMES = [
  'win',
  'losses',
  'triple',
  'chase_start_balanced',
  'first_innings_end_par',
  'commentary.analyst.strike_rotate',
  'commentary.analyst.strike_hold',
  'commentary.analyst.boundary_hold',
  'commentary.analyst.over_end_rotate',
  'commentary.analyst.new_batter',
  'commentary.analyst.partnership_building',
  'commentary.analyst.partnership_pressure',
  'commentary.analyst.partnership_release',
];

export const hasCommentaryPool = (role, poolName) => !!COMMENTARY_POOL_KEYS?.[role]?.[poolName]?.length;

export const getCommentaryPool = (role, poolName) => COMMENTARY_POOL_KEYS?.[role]?.[poolName] ?? [];

export const getLoadedCommentaryPool = (role, poolName, isAvailable = () => false) => (
  getCommentaryPool(role, poolName).filter((clipKey) => isAvailable(clipKey))
);

export const chooseRandomClipFromPool = (role, poolName, { exclude = null } = {}) => {
  const pool = getCommentaryPool(role, poolName);
  if (!pool.length) return null;
  const options = exclude && pool.length > 1 ? pool.filter((k) => k !== exclude) : pool;
  return options[Math.floor(Math.random() * options.length)] ?? null;
};

export const getCommentaryPoolValidationReport = ({ isAvailable = null, hasSound = null } = {}) => {
  const availabilityCheck = isAvailable || hasSound || (() => false);
  const report = [];
  for (const role of Object.keys(COMMENTARY_POOLS)) {
    for (const [poolName, expected] of Object.entries(COMMENTARY_POOLS[role])) {
      const configured = getCommentaryPool(role, poolName);
      const loaded = configured.filter((clipKey) => availabilityCheck(clipKey));
      report.push({ role, poolName, expected, configured: configured.length, loaded: loaded.length });
    }
  }
  const legacyRefs = LEGACY_POOL_NAMES.filter((name) => POOL_PRIORITY[name] || CMT_POOLS[name]);
  return { pools: report, legacyRefs };
};

export const logCommentaryPoolValidation = ({ isAvailable = null, hasSound = null } = {}) => {
  if (typeof __DEV__ === 'undefined' || !__DEV__) return;
  const availabilityCheck = isAvailable || hasSound || (() => false);
  const { pools, legacyRefs } = getCommentaryPoolValidationReport({ isAvailable: availabilityCheck });
  pools.forEach(({ role, poolName, expected, configured, loaded }) => {
    console.log('[commentary-validate]', { role, pool: poolName, expected, configured, loaded });
    if (loaded !== expected) {
      console.warn('[commentary-validate] pool mismatch', { role, pool: poolName, expected, loaded });
    }
  });
  if (legacyRefs.length) {
    console.warn('[commentary-validate] legacy pool refs detected', legacyRefs);
  }
};

export const LOOP_ASSETS = {
  menu: require('../../assets/sounds/sfx/menu.mp3'),
  ambientA: require('../../assets/sounds/sfx/ambient_sounds.mp3'),
  ambientB: require('../../assets/sounds/sfx/ambient_sounds.mp3'),
};
