export const ENABLE_SCREENSHOT_STUDIO = __DEV__;

/**
 * Build a staged lastOutcome for capture mode from dedicated outcomePanel mock data.
 * @param {object|null|undefined} preset
 * @returns {object|null}
 */
export const buildPresetLastOutcome = (preset) => {
  if (!preset) return null;

  const panel = preset.outcomePanel;
  if (panel?.title && panel?.body != null && panel?.rolled != null) {
    return {
      type: panel.type || 'runs',
      runs: panel.runs ?? 0,
      label: panel.title,
      detail: panel.body,
      clampedRoll: panel.rolled,
      dieLabel: panel.dieLabel || 'D6',
    };
  }

  return preset.lastOutcome || null;
};

export const SCREENSHOT_PRESETS = [
  {
    id: 'ready_to_roll',
    name: 'Ready To Roll',
    description: 'Pre-roll outcome panel before the dice is thrown.',
    pairing: ['northern_strikers', 'coastal_blaze'],
    innings: 1,
    runs: 42,
    wickets: 1,
    balls: 36,
    momentum: 1,
    selectedShot: 'drive',
    selectedAggression: 'balanced',
    selectedBowling: 'stock',
  },
  {
    id: 'hero_gameplay',
    name: 'Hero Gameplay',
    description: 'Clean mid-innings scoreboard with balanced match tension.',
    pairing: ['northern_strikers', 'coastal_blaze'],
    innings: 1,
    runs: 86,
    wickets: 2,
    balls: 58,
    momentum: 3,
    outcomePanel: {
      type: 'runs',
      runs: 2,
      title: '2 RUNS',
      body: 'Placed through the gap, two runs.',
      rolled: 5,
    },
  },
  {
    id: 'pressure_chase',
    name: 'Pressure Chase',
    description: 'Second innings with the required rate climbing.',
    pairing: ['southern_storm', 'east_midlands_knights'],
    innings: 2,
    target: 161,
    innings1Runs: 160,
    innings1Wickets: 8,
    innings1Balls: 120,
    runs: 118,
    wickets: 6,
    balls: 99,
    momentum: -4,
    overBalls: [
      { type: 'runs', runs: 1 },
      { type: 'dot', runs: 0 },
      { type: 'dot', runs: 0 },
    ],
    outcomePanel: {
      type: 'dot',
      runs: 0,
      title: 'DOT BALL',
      body: 'Missed outside off, good leave.',
      rolled: 1,
    },
  },
  {
    id: 'massive_six',
    name: 'Massive Six',
    description: 'Boundary moment with the last-ball panel primed.',
    pairing: ['south_east_royals', 'west_midlands_falcons'],
    innings: 1,
    runs: 104,
    wickets: 3,
    balls: 75,
    momentum: 6,
    selectedShot: 'power',
    selectedAggression: 'aggressive',
    overBalls: [
      { type: 'runs', runs: 1 },
      { type: 'four', runs: 4 },
      { type: 'six', runs: 6 },
    ],
    outcomePanel: {
      type: 'six',
      runs: 6,
      title: 'SIX!',
      body: 'Swivelled and pulled it over the rope! Audacious.',
      rolled: 9,
      dieLabel: 'D10',
    },
  },
  {
    id: 'wicket_moment',
    name: 'Wicket Moment',
    description: 'Wicket reveal ready for capture.',
    pairing: ['north_east_guardians', 'south_west_mariners'],
    innings: 1,
    runs: 72,
    wickets: 3,
    balls: 64,
    momentum: -3,
    gamePhase: 'wicket_pending',
    outcomePanel: {
      type: 'wicket',
      runs: 0,
      title: 'WICKET!',
      body: 'Sharp edge flies low to slip.',
      rolled: 1,
    },
    lastWicket: { type: 'CAUGHT SLIP', detail: 'Sharp edge flies low to slip.', roll: 5, drs: false },
  },
  {
    id: 'fifty_milestone',
    name: 'Fifty Milestone',
    description: 'Half-century celebration panel.',
    pairing: ['northern_strikers', 'coastal_blaze'],
    innings: 1,
    runs: 92,
    wickets: 1,
    balls: 70,
    momentum: 5,
    strikerRuns: 50,
    pendingMilestone: { runs: 50, batsmanName: 'Rylan Frost' },
    outcomePanel: {
      type: 'runs',
      runs: 2,
      title: '2 RUNS',
      body: 'Clipped neatly into the leg side to reach fifty.',
      rolled: 4,
    },
  },
  {
    id: 'match_win',
    name: 'Match Win',
    description: 'Celebratory result screen.',
    pairing: ['southern_storm', 'east_midlands_knights'],
    innings: 2,
    target: 160,
    innings1Runs: 159,
    innings1Wickets: 9,
    innings1Balls: 120,
    runs: 160,
    wickets: 5,
    balls: 111,
    momentum: 7,
    gamePhase: 'innings_end',
    deliveryPhase: 'innings_break',
  },
  {
    id: 'match_loss',
    name: 'Match Loss',
    description: 'Controlled dramatic defeat screen.',
    pairing: ['south_east_royals', 'west_midlands_falcons'],
    innings: 2,
    target: 168,
    innings1Runs: 167,
    innings1Wickets: 7,
    innings1Balls: 120,
    runs: 142,
    wickets: 10,
    balls: 116,
    momentum: -7,
    gamePhase: 'innings_end',
    deliveryPhase: 'innings_break',
  },
  {
    id: 'tie_result',
    name: 'Tie Result',
    description: 'Neutral dramatic scores-level result.',
    pairing: ['north_east_guardians', 'south_west_mariners'],
    innings: 2,
    target: 151,
    innings1Runs: 150,
    innings1Wickets: 8,
    innings1Balls: 120,
    runs: 150,
    wickets: 9,
    balls: 120,
    momentum: 0,
    gamePhase: 'innings_end',
    deliveryPhase: 'innings_break',
  },
  {
    id: 'weather_delay',
    name: 'Weather Delay',
    description: 'Special event card with a match interruption.',
    pairing: ['northern_strikers', 'coastal_blaze'],
    innings: 1,
    runs: 56,
    wickets: 2,
    balls: 43,
    momentum: -1,
    gamePhase: 'special_event',
    deliveryPhase: 'special_event',
    pendingEvent: {
      key: 'weather',
      label: 'WEATHER DELAY',
      icon: '🌧️',
      roll: 20,
      description: 'Rain interrupts play. The covers come on.',
      flavour: 'The ground staff sprint onto the field. Frustrating delay.',
      effect: { type: 'momentum', momentumDelta: -2, message: 'Weather delay — momentum cools slightly.' },
    },
    outcomePanel: {
      type: 'dot',
      runs: 0,
      title: 'DOT BALL',
      body: 'Play halted as rain sweeps across the ground.',
      rolled: 2,
    },
  },
  {
    id: 'chase_graph',
    name: 'Chase Graph',
    description: 'Scorecard view with both innings plotted.',
    pairing: ['north_east_guardians', 'south_west_mariners'],
    innings: 2,
    target: 174,
    innings1Runs: 173,
    innings1Wickets: 6,
    innings1Balls: 120,
    runs: 132,
    wickets: 5,
    balls: 92,
    momentum: -2,
    view: 'scorecard',
    innings1Series: [
      { ball: 6, runs: 11, wickets: 0 },
      { ball: 18, runs: 32, wickets: 0 },
      { ball: 30, runs: 55, wickets: 1 },
      { ball: 42, runs: 78, wickets: 1 },
      { ball: 54, runs: 94, wickets: 2 },
      { ball: 66, runs: 116, wickets: 2 },
      { ball: 78, runs: 139, wickets: 3 },
      { ball: 90, runs: 154, wickets: 4 },
      { ball: 102, runs: 165, wickets: 5 },
      { ball: 120, runs: 173, wickets: 6 },
    ],
    innings2Series: [
      { ball: 6, runs: 5, wickets: 0 },
      { ball: 18, runs: 18, wickets: 1 },
      { ball: 30, runs: 36, wickets: 1 },
      { ball: 42, runs: 49, wickets: 2 },
      { ball: 54, runs: 67, wickets: 2 },
      { ball: 66, runs: 84, wickets: 3 },
      { ball: 78, runs: 103, wickets: 4 },
      { ball: 86, runs: 119, wickets: 4 },
      { ball: 92, runs: 132, wickets: 5 },
    ],
    outcomePanel: {
      type: 'runs',
      runs: 1,
      title: '1 RUN',
      body: 'Worked into the gap to keep the chase alive.',
      rolled: 3,
    },
  },
  {
    id: 'scorecard_match_details',
    name: 'Scorecard / Match Details',
    description: 'Chase scorecard with top scorer, partnership, and target context.',
    captureLabel: 'Track every run, wicket and partnership',
    pairing: ['south_east_royals', 'west_midlands_falcons'],
    format: 'T20',
    innings: 2,
    target: 157,
    innings1Runs: 156,
    innings1Wickets: 7,
    innings1Balls: 120,
    runs: 132,
    wickets: 4,
    balls: 98,
    momentum: 5,
    view: 'scorecard',
    partnership: { runs: 52, balls: 34 },
    scorecardCaptureMeta: {
      tagline: 'Track every run, wicket and partnership',
      target: 157,
      needRuns: 25,
      needBalls: 22,
      reqRunRate: 6.82,
      partnershipRuns: 52,
      partnershipBalls: 34,
    },
    scorecardScenario: {
      currentBowlerIdx: 8,
      batting: [
        { index: 0, name: 'Alden Pierce', runs: 8, balls: 7, dismissal: 'BOWLED' },
        { index: 1, name: 'Keir Dalton', runs: 9, balls: 8, dismissal: 'CAUGHT' },
        { index: 2, name: 'Merric Stone', runs: 12, balls: 10, dismissal: 'c keeper b Archer' },
        { index: 3, name: 'Beck Brooks', runs: 4, balls: 3, dismissal: 'run out' },
        { index: 4, name: 'Finn Yew', runs: 78, balls: 52, fours: 9, sixes: 3, batting: true },
        { index: 5, name: 'Connor Wade', runs: 21, balls: 13, fours: 2, sixes: 0, batting: true },
      ],
      bowling: [
        { index: 8, name: 'Leo Archer', overs: 3.2, runs: 24, wickets: 1 },
        { index: 9, name: 'Saeed Malik', overs: 4, runs: 31, wickets: 2 },
        { index: 10, name: 'Orrin Knox', overs: 4, runs: 38, wickets: 1 },
        { index: 11, name: 'Pax Deller', overs: 5, runs: 39, wickets: 0 },
      ],
    },
    innings1Series: [
      { ball: 6, runs: 9, wickets: 0 },
      { ball: 18, runs: 28, wickets: 0 },
      { ball: 30, runs: 48, wickets: 1 },
      { ball: 42, runs: 66, wickets: 2 },
      { ball: 54, runs: 82, wickets: 2 },
      { ball: 66, runs: 101, wickets: 3 },
      { ball: 78, runs: 118, wickets: 4 },
      { ball: 90, runs: 134, wickets: 5 },
      { ball: 102, runs: 147, wickets: 6 },
      { ball: 120, runs: 156, wickets: 7 },
    ],
    innings2Series: [
      { ball: 6, runs: 8, wickets: 0 },
      { ball: 12, runs: 17, wickets: 0 },
      { ball: 24, runs: 33, wickets: 1 },
      { ball: 36, runs: 49, wickets: 2 },
      { ball: 48, runs: 61, wickets: 2 },
      { ball: 60, runs: 78, wickets: 3 },
      { ball: 72, runs: 94, wickets: 3 },
      { ball: 84, runs: 112, wickets: 4 },
      { ball: 90, runs: 121, wickets: 4 },
      { ball: 98, runs: 132, wickets: 4 },
    ],
  },
];

export const getScreenshotPreset = (presetId) =>
  SCREENSHOT_PRESETS.find((preset) => preset.id === presetId) || null;
