export const ENABLE_SCREENSHOT_STUDIO = __DEV__;

export const SCREENSHOT_PRESETS = [
  {
    id: 'hero_gameplay',
    name: 'Hero Gameplay',
    description: 'Clean mid-innings scoreboard with balanced match tension.',
    pairing: ['northern_strikers', 'coastal_blaze'],
    innings: 1,
    runs: 86,
    wickets: 2,
    balls: 58,
    momentum: 3,
    lastOutcome: { type: 'four', runs: 4, label: 'FOUR!', detail: 'Threaded through cover with perfect timing.', clampedRoll: 5, dieLabel: 'D6' },
  },
  {
    id: 'pressure_chase',
    name: 'Pressure Chase',
    description: 'Second innings with the required rate climbing.',
    pairing: ['southern_storm', 'east_midlands_knights'],
    innings: 2,
    target: 161,
    innings1Runs: 160,
    innings1Wickets: 8,
    innings1Balls: 120,
    runs: 118,
    wickets: 6,
    balls: 99,
    momentum: -4,
    overBalls: [
      { type: 'runs', runs: 1 },
      { type: 'dot', runs: 0 },
      { type: 'dot', runs: 0 },
    ],
    lastOutcome: { type: 'dot', runs: 0, label: 'DOT BALL', detail: 'Beaten by a tight line outside off.', clampedRoll: 1, dieLabel: 'D6' },
  },
  {
    id: 'massive_six',
    name: 'Massive Six',
    description: 'Boundary moment with the last-ball panel primed.',
    pairing: ['south_east_royals', 'west_midlands_falcons'],
    innings: 1,
    runs: 104,
    wickets: 3,
    balls: 75,
    momentum: 6,
    selectedShot: 'power',
    selectedAggression: 'aggressive',
    overBalls: [
      { type: 'runs', runs: 1 },
      { type: 'four', runs: 4 },
      { type: 'six', runs: 6 },
    ],
    lastOutcome: { type: 'six', runs: 6, label: 'SIX!', detail: 'Launched high into the night sky and into the stands.', clampedRoll: 6, dieLabel: 'D6' },
  },
  {
    id: 'wicket_moment',
    name: 'Wicket Moment',
    description: 'Wicket reveal ready for capture.',
    pairing: ['north_east_guardians', 'south_west_mariners'],
    innings: 1,
    runs: 72,
    wickets: 3,
    balls: 64,
    momentum: -3,
    gamePhase: 'wicket_pending',
    lastOutcome: { type: 'wicket', runs: 0, label: 'WICKET!', detail: 'Sharp edge flies low to slip.', clampedRoll: 1, dieLabel: 'D6' },
    lastWicket: { type: 'CAUGHT SLIP', detail: 'Sharp edge flies low to slip.', roll: 5, drs: false },
  },
  {
    id: 'fifty_milestone',
    name: 'Fifty Milestone',
    description: 'Half-century celebration panel.',
    pairing: ['northern_strikers', 'coastal_blaze'],
    innings: 1,
    runs: 92,
    wickets: 1,
    balls: 70,
    momentum: 5,
    strikerRuns: 50,
    pendingMilestone: { runs: 50, batsmanName: 'Rylan Frost' },
    lastOutcome: { type: 'runs', runs: 2, label: '2 RUNS', detail: 'Clipped neatly into the leg side to reach fifty.', clampedRoll: 4, dieLabel: 'D6' },
  },
  {
    id: 'match_win',
    name: 'Match Win',
    description: 'Celebratory result screen.',
    pairing: ['southern_storm', 'east_midlands_knights'],
    innings: 2,
    target: 160,
    innings1Runs: 159,
    innings1Wickets: 9,
    innings1Balls: 120,
    runs: 160,
    wickets: 5,
    balls: 111,
    momentum: 7,
    gamePhase: 'innings_end',
    deliveryPhase: 'innings_break',
  },
  {
    id: 'match_loss',
    name: 'Match Loss',
    description: 'Controlled dramatic defeat screen.',
    pairing: ['south_east_royals', 'west_midlands_falcons'],
    innings: 2,
    target: 168,
    innings1Runs: 167,
    innings1Wickets: 7,
    innings1Balls: 120,
    runs: 142,
    wickets: 10,
    balls: 116,
    momentum: -7,
    gamePhase: 'innings_end',
    deliveryPhase: 'innings_break',
  },
  {
    id: 'tie_result',
    name: 'Tie Result',
    description: 'Neutral dramatic scores-level result.',
    pairing: ['north_east_guardians', 'south_west_mariners'],
    innings: 2,
    target: 151,
    innings1Runs: 150,
    innings1Wickets: 8,
    innings1Balls: 120,
    runs: 150,
    wickets: 9,
    balls: 120,
    momentum: 0,
    gamePhase: 'innings_end',
    deliveryPhase: 'innings_break',
  },
  {
    id: 'weather_delay',
    name: 'Weather Delay',
    description: 'Special event card with a match interruption.',
    pairing: ['northern_strikers', 'coastal_blaze'],
    innings: 1,
    runs: 56,
    wickets: 2,
    balls: 43,
    momentum: -1,
    gamePhase: 'special_event',
    deliveryPhase: 'special_event',
    pendingEvent: {
      key: 'weather',
      label: 'WEATHER DELAY',
      icon: '🌧️',
      roll: 20,
      description: 'Rain interrupts play. The covers come on.',
      flavour: 'The ground staff sprint onto the field. Frustrating delay.',
      effect: { type: 'momentum', momentumDelta: -2, message: 'Weather delay — momentum cools slightly.' },
    },
  },
  {
    id: 'chase_graph',
    name: 'Chase Graph',
    description: 'Scorecard view with both innings plotted.',
    pairing: ['north_east_guardians', 'south_west_mariners'],
    innings: 2,
    target: 174,
    innings1Runs: 173,
    innings1Wickets: 6,
    innings1Balls: 120,
    runs: 132,
    wickets: 5,
    balls: 92,
    momentum: -2,
    view: 'scorecard',
    innings1Series: [
      { ball: 6, runs: 11, wickets: 0 },
      { ball: 18, runs: 32, wickets: 0 },
      { ball: 30, runs: 55, wickets: 1 },
      { ball: 42, runs: 78, wickets: 1 },
      { ball: 54, runs: 94, wickets: 2 },
      { ball: 66, runs: 116, wickets: 2 },
      { ball: 78, runs: 139, wickets: 3 },
      { ball: 90, runs: 154, wickets: 4 },
      { ball: 102, runs: 165, wickets: 5 },
      { ball: 120, runs: 173, wickets: 6 },
    ],
    innings2Series: [
      { ball: 6, runs: 5, wickets: 0 },
      { ball: 18, runs: 18, wickets: 1 },
      { ball: 30, runs: 36, wickets: 1 },
      { ball: 42, runs: 49, wickets: 2 },
      { ball: 54, runs: 67, wickets: 2 },
      { ball: 66, runs: 84, wickets: 3 },
      { ball: 78, runs: 103, wickets: 4 },
      { ball: 86, runs: 119, wickets: 4 },
      { ball: 92, runs: 132, wickets: 5 },
    ],
    lastOutcome: { type: 'runs', runs: 1, label: '1 RUN', detail: 'Worked into the gap to keep the chase alive.', clampedRoll: 3, dieLabel: 'D6' },
  },
];

export const getScreenshotPreset = (presetId) =>
  SCREENSHOT_PRESETS.find((preset) => preset.id === presetId) || null;
